version: '3.8'

services:
    api:
        image: node:16
        command: sh -c "npx prisma migrate dev && npm run dev"
        ports:
            - 3000:3000
        working_dir: /api
        stdin_open: true
        tty: true
        networks:
            - db-connection
        volumes:
            - ./api:/api
        environment:
            APP_HOST: $API_HOST
            APP_PORT: $API_PORT
            DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}'
        links:
            - db
        depends_on:
            - db
        env_file:
            - ./.env

    db:
        image: mysql/mysql-server:8.0
        volumes:
            - krutz-data:/var/lib/mysql
        ports:
            - 3306:3306
        restart: unless-stopped
        stdin_open: true
        tty: true
        environment:
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
            MYSQL_USER_HOST: "%"
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - db-connection
        volumes:
            - krutz-db:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        env_file:
            - ./.env

volumes:
    krutz-db:

networks:
    db-connection:
        driver: bridge