version: '3.8'

services:
    api:
        image: node:16
        command: sh -c "npx prisma migrate dev && npm run dev"
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_DB: krutz

    mysql:
        image: mysql:latest
        volumes:
            - krutz-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: krutz

volumes:
    krutz-data:
